version: "3.8"

networks:
  app_misha_network:
    name: app_misha_network
    driver: bridge


services:
  db_misha:
    image: postgres:15-alpine3.21
    container_name: db_misha
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app_misha_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}' ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    driver: local